-- CreateTable (Postgres)
CREATE TABLE "Trade" (
    "id" SERIAL PRIMARY KEY,
    "symbol" TEXT NOT NULL,
    "direction" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "entryDate" TIMESTAMP(3) NOT NULL,
    "entryTime" TEXT NOT NULL,
    "entryPrice" DOUBLE PRECISION NOT NULL,
    "exitDate" TIMESTAMP(3) NOT NULL,
    "exitTime" TEXT NOT NULL,
    "exitPrice" DOUBLE PRECISION NOT NULL,
    "duration" TEXT NOT NULL,
    "pnl" DOUBLE PRECISION NOT NULL,
    "percentChange" DOUBLE PRECISION NOT NULL,
    "orderType" TEXT NOT NULL,
    "assessment" TEXT,
    "capital" DOUBLE PRECISION NOT NULL,
    "notes" TEXT,
    "strategy" TEXT,
    "riskReward" TEXT,
    "commission" DOUBLE PRECISION,
    "tags" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);
